server:
  port: 8082
spring:
  application:
    name: Inventory-Management

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:9096/eureka