server:
  port: 8089
spring:
  application:
    name: Inventory-Management
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_management
    username: root
    password: Secure*123
  jpa:
    generate-ddl: false
    show-sql: true  

#Microservice eureka registraiton configuration.
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9096/eureka/


